repos:
# -   repo: https://github.com/pre-commit/mirrors-isort
#     rev: master
#     hooks:
#     - id: isort
#       require_serial: true

-   repo: https://github.com/PyCQA/flake8
    rev: master
    hooks:
    - id: flake8
      require_serial: true

-   repo: https://github.com/python/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
      require_serial: true
    
